title = "Style configuration"

###### style values
[style.colors] 
GREEN = "#6E9B87"
ORANGE = "#EE6C4D"
BLUEWHITE = "#F0F6F9"
BLUELIGHT = "#D2E4EE"
BLUEMEDIUM = "#3D4A80"
BLUEDARK = "#293241"
GREYLIGHT = "#EBEBEB"
GREYMEDIUM1 = "#91969D"
GREYMEDIUM2 = "#767C85"
GREYDARK = "#545B67"
BORDERGREY = "#797979"
BLACK = "#000000"
WHITE = "#FFFFFF"
GREYEXTRALIGHT = "#F0F6F9"

[style.dimension]
WINMAXWIDTH = 1100
WINMAXHEIGHT = 900
BTNWIDTH = 150
BTNHEIGHT = 40
SBTNWIDTH = 100
SBTNHEIGHT  = 30 
LBTNWIDTH = 200
CONSOLEWIDTH = 1000
CONSOLEHEIGHT = 300
STATUSWIDTH = 900
STATUSHEIGHT = 30 
INPUTWIDTH = 200
INPUTHEIGHT = 30
ICONBTN = 50
TABLEWIDTH = 900
TABLEMINHEIGHT = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH = 400
PROGRESSBARHEIGHT = 40
LARGEDIALOGWIDTH = 850
LARGEDIALOGHEIGHT = 800

[style.fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL="11px"
LINK = "15px"
HEADER1 = "32px" 
HEADER2  = "24px"
HEADER3  = "18px"
TABLE_ROW = "13px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px" 
SETTINGICON = "40px"

[style.fontFamily]
 MAIN = "Raleway"
 OTHER = "Helvetica"

[style.styleSheet]
"goToMain" = "border:none; color:#3D4A80;"
"settingStackID" ="settingStack"
"settingStack" = "#settingStack {border: none; border-left:0.5px solid grey;}"
"sysSettingStackID" = "sysForm"
"sysSettingStack" = "#sysForm {border: none; border-left:0.5px solid grey;}"
"noSideBorder" = "border-left:none; border-right:none;"
"boldTopBorder" = "border-top: 1px solid #545B67;"
"boldBottomBorder" = "border-bottom: 2px solid #545B67;"
"onlyBottomBorder" = "border-left:none; border-right:none; border-top:none;"
"onlyTopBorder"  = "border-left:none; border-right:none; border-bottom:none;"
"buttonList" = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px"
"dropDownBtn" = "margin-top:0px;border-radius:0px;padding:5px"

###### text values 
[text.links]
HILAB = "https://sites.tufts.edu/hilab"

[text.TranscribeSuccessText]
mainLabelText = "Transcription Successful"
transcribedFilesText = "Transcribed files and locations:"
moreBtnText = "Process more files"
returnBtnText = "Return to main menu"

[text.TranscribeProgressText]
mainLabelText = "Transcription in Progress"
loadingText = "Transcribing files..."
inProgressText = "Files in progress:"
cancelText = "Cancel"

[text.WelcomePageText]
audioInstructionText = "1. Select audio and video files \n or record live in Gailbot"
settingsInstructionText = "2. Apply settings"
transcribeInstructionText = "3. Transcribe"
fileInstructionText = "4. Get a transcribed file"
editInstructionText = "5. Edit settings \n or retranscribe"
welcomeText = "Welcome to GailBot"
captionText = "GailBot is the world's first application that lets you convert audio and\n video files into customizd transcripts."
startBtnText = "Get Started"
instructionText = "How GailBot Works"
resourcesText = "Resources"
tutorialText = "GailBot Beginner Tutorial"
guideText = "GailBot Settings Guide"
gbLinkText = "GailBot.com"
moreInfoText = "For more information visit"

[text.FileUploadPageText]
header = "Files to Transcribe"
returnMainText = "Return to Main Menu"
recordBtnText = "Record live"
uploadBtnText = "Add From Device"
transcribeBtnText = "Transcribe"
removeBtnText = "Remove All"
settingBtnText = "âš™"
dropText = "Drop File Here to Upload"
chooseLocalText = "Choose From Local"
chooseSetHeader = "select setting profile"
selectSetText = "select settings"
selectPlaceHolderText = "None"
selectFolderText = "Select Folder"
chooseOutPutText = "Choose Output Directory"
fileFilter = ["audio file (*.wav)","directory (/)"]
removeWarnText = "Remove all files?"

[text.RecordPageText]
basic = "Basic"
filename = "Filename"
mp3 = "MP3"
wav = "WAV"
format = "Audio Format"
advanced = "Advanced"
rate = "Recording Rate (Hertz)"
duration = "Max Recording Duration"
cancel = "Cancel"
start = "Start Recording"
test = "Test MicroPhone"
recSet = "Recording Settings"
record = "Record Audio File"
end = "End Recording"

[text.ProfilePageText]
cancelBtn = "Cancel"
saveBtn = "Save and Exit"
newProfileBtn = "Create New Profile"
reuquiredSetBtn = "Required Settings"
postSetBtn = "Post-Transcription Settings"
newPluginBtn = "Add New Plugin"
pluginSetBtn = "Plugin Setting"
postSetHeader = "Post-Transcription Settings"
postSetCaption = "These settings are applied after the file is created."
requiredSetHeader =  "Required Settings"
requiredSetCaption =  "These settings are required before transcription and cannot be edited after transcription."
pluginHeader = "Choose Plugins"
pluginCaption = "These plugins are applied to transcription process"

[text.SystemSettingPage]
header = "System Setting"
caption = "These settings are applied for system setting"
cancelBtn = "Cancel"
saveBtn = "Save and Exit"

[text.ConfirmTranscriptionPageText]
confirmLabel = "Confirm Files and Settings"
confirm = "Confirm"
cancel = "Cancel"

[text.RecordInProgressPageText]
start = "Start Recording"
cancel = "Cancel"
end = "End Recording"

#################   TODO: insert values #################
[text.CreateNewProfilePageText]  
confirmProfileNameBtn = "Start"
emptyNameMsg = "The profile name cannot be empty"
emptyUserMsg = "Please enter user name and password"
engineSettingHeader = "Speech to text settings"
outputSettingHeader =  "Output format settings"
cofirmBtn = "confirm"

[text.ChooseFileTabText]
WindowTitle = "Upload File"
TabTitle    = "Add New File"
TabHeader1  = "add file"
TabHeader2  = "choose setting"
TabHeader3  = "select output"

[text.WindowTitle]
consoleWindow = "Console Window"

[text.CreateNewProfileText]
WindowTitle = "Create New Profile"
TabTitle = "Create New Profile"
TabHeader1 = "Profile Name"
TabHeader2 = "Basic Settings"
TabHeader3 = "Optional Settings"
TabHeader4 = "Output File Format Setting"
TabHeader5 = "Post Transcribtion Settion"
TabHeader6 = "Plugin Setting"

[text.MainStackText]
ProfileSettingBtn = "Porfile Setting"
SystemSettingBtn  = "System Setting"

[text.OutputFormatForm]
header = "Output File Format"
CorpuFormHeader = "Corpus Settings"
LanguageHeader  = "language"
FileFormatHeader = "File Format"
SpeakerHeader = "Number of Speaker"
TextWrap = "Text-Wrapping"

[text.RequiredSettingForm]
engineSetHeader = "Speech to text settings"
outputSetHeader = "Output File Format Settings"

###### form values
["profile form".Plugins]
HiLabSuite = "https://sites.tufts.edu/hilab/files/2022/05/HiLabSuite.zip"

["profile form"."PostTranscribe".General]
"Gap Length" = "0s"
"Turn End Threshold" = "0s"
"Large Pause - Lower Bound" = "0s"

["profile form"."PostTranscribe"."Laghter Settings"]
"Laughter Detection Module bool" = "ON"
"Laughter Probability - Lower Bound" = "0s"
"Laughter Length - Lower Bound" = "0s"

["profile form"."PostTranscribe"."MicroPause Bound"]
"Upper Bound" = "0s"
"Lower Bound" = "0s"

["profile form"."PostTranscribe"."Transcription Model"]
"Beat Transcription Mode bool" = "ON"
"FTO (Floor Transfer offset)Transcription Mode bool" = "ON"
"Syllable Rate mode bool" = "ON"

["profile form"."RequiredSetting"."Output Format".CorpusSettings]
"Corpus name" = "enter corpus name"
"Corpus location" = "enter corpus location"
"Corpus room layout" = "enter corous room layout"
"Corpus situation" = "enter situation"

["profile form"."RequiredSetting"."Output Format"]
"FileFormat" = ["CHART", "TXT", "RTF"]
"Language" = ["English", "French", "Spanish", "German", "Chinese(Madarin)", "Chinese(Cantonese)"]


["profile form"."RequiredSetting".Engine.IBM."1.language model setting"]
"1. language model" = [ "IBM language", "English", "Spanish",]
"2. costum language model" = [ "HRI lab", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.IBM."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]

["profile form"."RequiredSetting".Engine.IBM."3.advanced setting"]
"1. Advanced Setting Option 1" = [ "advanced 1", "advanced 2", "advanced 3",]
"2. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.IBM."4.IBM specialised setting"]
"IBM dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["profile form"."RequiredSetting".Engine.CMU."1.language model setting"]
"1. language model" = [ "CMU language", "English", "Spanish",]
"2. costum language model" = [ "CMU costum", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.CMU."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]
"3. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.CMU."3.CMU specialised setting"]
"CMU dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["system setting form"."General Setting"]
"Font Size combo" = [ "small", "medium", "big",]
"Color Mode combo" = [ "default", "dark", "light",]
"Large Pause - Lower Bound" = "0s"

["system setting form"."Dummy Setting Options"]
"Dummy on and off bool" = "ON"
"Dummy input" = "dummy"
"Dummy selection mode combo" = [ "selection1", "selection2", "selection3",]

[filetable.header]
"fileUploadPage" = ["Select All", "Type", "Name", "Profile", 
                    "Status", "Date", "Size", "Actions"]
"confirmPage"  = ["Type", "Name", "Profile", "SelectedAction", "Action"]
"transcribePage" = ["Type", "Name", "Progress"]
"successPage"   =  ["Type",  "Name", "Status", "Output"]


[filetable.dimension]
"fileUploadPage" = [0.07,0.07,0.2,0.15,0.15,0.08,0.08,0.2]
"confirmPage"    = [0.1,0.35,0.25,0.13,0.17]
"transcribePage" = [0.2, 0.55, 0.25]
"successPage"   =  [0.17, 0.35, 0.25, 0.23]

[asset]
"arrowImg" = "arrow.png"
"subPageBackgorund" = "backgroundConfirmPage.png"
"trashImg" = "trash.png"
"mainBackground" = "background.png"

[about]
"version" = "1.0.0"


####widgets
[text.btnText]
on = "ON"
off = "OFF"
icon = "iconButton"
right = "right.png"
down = "down.png"